### ISSUE TITLE
Error in the user_hooks.rb file

### ISSUE THREAD

**Issue by nvsu** [YukiKita/redmine_niko_cale#20]
I run the "rake db:migrate_plugins RAILS_ENV=production" and below error are raised.
SyntaxError: /redmine-3.4.6/plugins/redmine_niko_cale/lib/user_hooks.rb:8: syntax error, unexpected <<
      header_and_image = <<~EOS
Please help to fix it. 
Thank you very much.

**Comment by YukiKita** [comment]
This seems to be a Ruby version issue.
Your Ruby interpreter seems to be unable to handle <<~ which is a new heredoc format announced at Ruby 2.3.0.
What Ruby version are you using?

https://bugs.ruby-lang.org/issues/9098

**Comment by nvsu** [comment]
thank you very for your information.
I am using ruby 「2.2.6p396 (2016-11-15 revision 56800) [i386-mingw32]」.
I will try to test on the latest ruby version.

Thank you.
